#!/bin/bash

cmake -B build/ -S .
make -C build/
cd testes/libs; make -s
cd ..     # back to directory 'testes'
ulimit -S -s 1100
if { ../build/lua -W all.lua; } then
  echo -e "\n\n    final OK!!!!\n\n"
else
  echo -e "\n\n    >>>> BUG!!!!\n\n"
fi
